SELECT ORDER_ID ORDENES, ORDER_DATE "FECHA DE ORDEN", ORDER_TOTAL "TOTAL DE LA ORDEN"
FROM OE.ORDERS
WHERE ORDER_DATE LIKE '%JUN-07%' AND ORDER_TOTAL >= 10000;

SELECT CUST_FIRST_NAME NOMBRE, 
  CUST_LAST_NAME APELLIDO, 
  NLS_TERRITORY PAIS, 
  INCOME_LEVEL INGRESO 
FROM 
  OE.CUSTOMERS 
WHERE 
  NLS_TERRITORY NOT LIKE '%AMERICA%' 
  AND (INCOME_LEVEL >= 170000 AND INCOME_LEVEL <= 250000);

SELECT ORDER_ID "ID DE ORDEN", QUANTITY CANTIDAD FROM OE.ORDER_ITEMS
WHERE QUANTITY >=10
ORDER BY QUANTITY ASC;

SELECT PRODUCT_NAME "NOMBRE DE PRODUCTO", PRODUCT_DESCRIPTION "DESCRIPCION", LIST_PRICE "PRECIO DE LISTA"
FROM OE.PRODUCT_INFORMATION
WHERE (PRODUCT_DESCRIPTION LIKE '%PRINTER%') AND LIST_PRICE BETWEEN 100 AND 250;

SELECT CUST_FIRST_NAME ||' '|| CUST_LAST_NAME AS "NOMBRE COMPLETO",NLS_TERRITORY PAIS, ACCOUNT_MGR_ID AGENTE
FROM OE.CUSTOMERS
WHERE NLS_TERRITORY LIKE '%GERMANY%' AND ACCOUNT_MGR_ID = '147';

SELECT CUST_FIRST_NAME ||' '|| CUST_LAST_NAME AS "NOMBRE COMPLETO" FROM OE.CUSTOMERS
WHERE CUST_FIRST_NAME LIKE 'H%' AND CUST_LAST_NAME LIKE 'P%';

SELECT CUST_FIRST_NAME ||' '|| CUST_LAST_NAME AS "NOMBRE COMPLETO", CUST_EMAIL EMAIL FROM OE.CUSTOMERS
WHERE CUST_EMAIL LIKE 'GO%';


SELECT CUST_FIRST_NAME ||' '|| CUST_LAST_NAME AS "NOMBRE COMPLETO", NLS_TERRITORY AS PAIS,
CREDIT_LIMIT "LIMITE DE CREDITO" FROM OE.CUSTOMERS
WHERE 