#Repaso guias

select job_id codigo, job_title cargo, min_salary "Salario Minimo", max_salary "Salario Maximo" 
from hr.jobs
where min_salary >= 10000;

select first_name Nombre, last_name Apellido, hire_date "Fecha de Contratation" from hr.employees
	where hire_date like '%JUL-87%' 
	and hire_date like '%AUG-87%'
    order by hire_date asc;

SELECT first_name "Nombre",last_name "Apellido", hire_date "Fecha de Contratacion"
FROM hr.employees
WHERE job_id IN ('IT_PROG', 'SA_MAN')
ORDER BY job_id ASC;

SELECT * FROM HR.EMPLOYEES
WHERE HIRE_DATE > '01-SEP-87';

SELECT * FROM HR.EMPLOYEES 
WHERE EMPLOYEE_ID LIKE '%150%' OR EMPLOYEE_ID LIKE '%160%' 
ORDER BY EMPLOYEE_ID ASC;

SELECT FIRST_NAME NOMBRE, LAST_NAME APELLIDO, SALARY SUELDO, COMMISSION_PCT COMISION FROM HR.EMPLOYEES
WHERE SALARY <= 10000;

SELECT DISTINCT FIRST_NAME NOMBRE, LAST_NAME APELLIDO, SALARY SUELDO, COMMISSION_PCT COMISION FROM HR.EMPLOYEES
WHERE SALARY <= 10000;

SELECT JOB_TITLE TITULO, MIN_SALARY "SALARIO MINIMO",
MAX_SALARY "SALARIO MAXIMO",(MAX_SALARY - MIN_SALARY) DIFERENCIA FROM HR.JOBS 
WHERE MAX_SALARY BETWEEN 10000 AND 20000;

SELECT JOB_TITLE AS CARGO FROM HR.JOBS
ORDER BY JOB_TITLE DESC;

SELECT FIRST_NAME AS NOMBRE FROM HR.EMPLOYEES
WHERE FIRST_NAME LIKE 'S%';

SELECT HIRE_DATE AS "FECHA DE CONTRATACION" FROM HR.EMPLOYEES
WHERE HIRE_DATE LIKE '%MAY%';

SELECT EMPLOYEE_ID "ID CARGO", 
  DEPARTMENT_ID DEPARTAMENTO, 
  COMMISSION_PCT COMISION, 
  SALARY SALARIO 
FROM HR.EMPLOYEES 
WHERE (COMMISSION_PCT IS NULL) 
  AND (SALARY BETWEEN 5000 AND 10000);

SELECT FIRST_NAME NOMBRE, LAST_NAME APELLIDO, HIRE_DATE "FECHA DE CONTRATACION", 
(15-JUL-24 - HIRE_DATE) AS "AÑOS DE EXPERIENCIA" FROM HR.EMPLOYEES;

SELECT FIRST_NAME AS NOMBRE, 
  LAST_NAME AS APELLIDO, 
  HIRE_DATE AS "FECHA DE CONTRATACION", 
  TRUNC(MONTHS_BETWEEN(SYSDATE, HIRE_DATE) / 12) AS "AÑOS DE EXPERIENCIA"
FROM HR.EMPLOYEES;