SELECT CUST_FIRST_NAME NOMBRE, CUST_LAST_NAME APELLIDO, NLS_TERRITORY PAIS
FROM OE.CUSTOMERS
WHERE NLS_TERRITORY NOT LIKE '%AMERICA%';

SELECT CUST_FIRST_NAME NOMBRE, CUST_LAST_NAME APELLIDO, CREDIT_LIMIT "LIMITE DE CREDITO"
FROM OE.CUSTOMERS
WHERE CREDIT_LIMIT BETWEEN 300 AND 500
ORDER BY CREDIT_LIMIT ASC;

SELECT CUST_FIRST_NAME NOMBRE, CUST_LAST_NAME APELLIDO, PHONE_NUMBERS "NUMERO DE TELEFONO"
FROM OE.CUSTOMERS
WHERE PHONE_NUMBERS LIKE '%+91%';

SELECT 
  CUST_FIRST_NAME AS NOMBRE,
  CUST_LAST_NAME AS APELLIDO,
  PHONE_NUMBERS AS "NUMERO DE TELEFONO"
FROM 
  OE.CUSTOMERS
WHERE 
  PHONE_LIST_TYP LIKE '%+91%';

  SELECT CUST_FIRST_NAME NOMBRE, CUST_LAST_NAME APELLIDO FROM OE.CUSTOMERS
  WHERE CUST_FIRST_NAME LIKE 'H%' AND CUST_LAST_NAME LIKE 'P%';

SELECT CUST_FIRST_NAME NOMBRE, CUST_LAST_NAME APELLIDO, CUST_EMAIL AS "CORREO ELECTRONICO" FROM OE.CUSTOMERS
WHERE CUST_EMAIL LIKE '%GO%';

SELECT CUST_FIRST_NAME NOMBRE, CUST_LAST_NAME APELLIDO, NLS_TERRITORY PAIS, CREDIT_LIMIT AS "LIMITE DE CREDITO"
FROM OE.CUSTOMERS
WHERE NLS_TERRITORY LIKE '%GERMANY%' OR NLS_TERRITORY LIKE '%ITALY%'
AND CREDIT_LIMIT >= 2000; 






